In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv(r"C:\Users\HONOR\Downloads\MR data - Compiled Data Set.csv")
df.head()

,City,Title,Text,"Murder Happened with reason:\n1:Property/Land Disputes,\n2:Family Dispute\n3:Petty Quarrels,\n4:Money Disputes, \n5:Personal Vendetta, \n6:Love Affairs, \n7:Casteism\n8: Unknown/other",Number of child victims,Number of male victims(adult),Number of female victims(adult),Kidnnaping:\nNumber of child victims,Number of male(adult),Number of female(adult),Crime Against Women ( Combined ):\n1. Murder with Rape \n2. Dowry Deaths(Sec. 3048)\n3. Suicide(sec 305/306)\n4. Kidnapping(All)\n5. Acid Attack(Sec. 326A IPC)\n6. Cruelty by Husband/in-laws((Sec.498 A IPC)\n7. Rape only(Sec. 376 or 511 IPC)\n8. Assault on Women with Intent to Outrage her Modesty (Sec. 354 IPC)\n9. Cyber Crimes against Women\n10. Protection of Children from Sexual Offences Act,Number of adult victims,Number of childs invoved
0,Ghaziabad,"Minor molests mute girl, sent to observation home",GHAZIABAD: A 12-year-old boy was sent to an ob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"8,10",NaN,3.0
1,Ghaziabad,Family out to buy car robbed of Rs 1 lakh by b...,GHAZIABAD: A family that had visited an automo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ghaziabad,"This gang posed as cops to extort youths, couples",GHAZIABAD: Five persons were arrested on Monda...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ghaziabad,"Residents object to loud music, thrashed in Gh...","Ghaziabad: Four tenants, including two soldier...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ghaziabad,Man kills self after being refused money for d...,GHAZIABAD: A 25-year-old allegedly committed s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.shape

(466, 13)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466 entries, 0 to 465
Data columns (total 13 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                              --------------  -----
 0   City                                                                                                                                                                                                                                                                                                                                                                                                466 non-null    object
 1   Title                                                                                                                                                                                                                                                                                                                                                                                               466 non-null    object
 2   Text                                                                                                                                                                                                                                                                                                                                                                                                466 non-null    object
 3   Murder Happened with reason:
1:Property/Land Disputes,
2:Family Dispute
3:Petty Quarrels,
4:Money Disputes,
5:Personal Vendetta,
6:Love Affairs,
7:Casteism
8: Unknown/other                                                                                                                                                                                                                     147 non-null    object
 4   Number of child victims                                                                                                                                                                                                                                                                                                                                                                             13 non-null     float64
 5   Number of male victims(adult)                                                                                                                                                                                                                                                                                                                                                                       95 non-null     float64
 6   Number of female victims(adult)                                                                                                                                                                                                                                                                                                                                                                     47 non-null     float64
 7   Kidnnaping:
Number of child victims                                                                                                                                                                                                                                                                                                                                                                 11 non-null     float64
 8   Number of male(adult)                                                                                                                                                                                                                                                                                                                                                                               8 non-null      float64
 9   Number of female(adult)                                                                                                                                                                                                                                                                                                                                                                             3 non-null      float64
 10  Crime Against Women ( Combined ):
1. Murder with Rape
2. Dowry Deaths(Sec. 3048)
3. Suicide(sec 305/306)
4. Kidnapping(All)
5. Acid Attack(Sec. 326A IPC)
6. Cruelty by Husband/in-laws((Sec.498 A IPC)
7. Rape only(Sec. 376 or 511 IPC)
8. Assault on Women with Intent to Outrage her Modesty (Sec. 354 IPC)
9. Cyber Crimes against Women
10. Protection of Children from Sexual Offences Act  200 non-null    object
 11  Number of adult victims                                                                                                                                                                                                                                                                                                                                                                             116 non-null    float64
 12  Number of childs invoved                                                                                                                                                                                                                                                                                                                                                                            85 non-null     float64
dtypes: float64(8), object(5)
memory usage: 47.5+ KB

In [4]:
df.columns= df.columns.str.strip()
df.columns= ['city','title','text','murder_reason','murder_child_victims','murder_male_adult_victims','murder_female_adult_victims',
              'kidnap_child_victims', 'kidnap_male_adult_victims', 'kidnap_female_adult_victims',
              'crime_against_women_type', 'total_adult_victims', 'total_child_victims']

In [5]:
numeric_cols=['murder_child_victims','murder_male_adult_victims','murder_female_adult_victims',
                 'kidnap_child_victims', 'kidnap_male_adult_victims', 'kidnap_female_adult_victims',
                 'total_adult_victims', 'total_child_victims']
df[numeric_cols] = df[numeric_cols].fillna(0).astype(int)
category_cols = ['murder_reason','crime_against_women_type']
df[category_cols]= df[category_cols].fillna('Not Applicable')
df.isnull().sum()

city                           0
title                          0
text                           0
murder_reason                  0
murder_child_victims           0
murder_male_adult_victims      0
murder_female_adult_victims    0
kidnap_child_victims           0
kidnap_male_adult_victims      0
kidnap_female_adult_victims    0
crime_against_women_type       0
total_adult_victims            0
total_child_victims            0
dtype: int64

In [6]:
df['city'].unique()

array(['Ghaziabad', 'Kanpur', 'Lucknow'], dtype=object)

In [7]:
df['murder_reason'].unique()

array(['Not Applicable', 'Money Disputes', 'Love Affairs',
       'Unknown reasons', 'Petty Quarrels', 'Property Disputes',
       'Family Dispute', 'Personal Vendetta', 'Casteism'], dtype=object)

In [8]:
df['murder_reason'] = df['murder_reason'].replace({'Unknown reasons': 'Unknown/Other', 
                                                   'Property Dispute': 'Property/Land Disputes'})
df['murder_reason'].unique()

array(['Not Applicable', 'Money Disputes', 'Love Affairs',
       'Unknown/Other', 'Petty Quarrels', 'Property Disputes',
       'Family Dispute', 'Personal Vendetta', 'Casteism'], dtype=object)

In [9]:
df['crime_against_women_type'].unique()

array(['8,10', 'Not Applicable', '10', '9', '4,7', '4', '7', '1,10', '8',
       '3', '7,10', '2,3,6', '6', '1,4,10', '2', '5,6', '1, 10', '5',
       '8, 10', '11', '2,3', '7,9', '3,7,10', '7, 10', '2,6', '1', '4,8',
       '3,7', '3,8', '7,8', '1,4', '6, 8', '4,7,10', '8,9'], dtype=object)

In [10]:
df['crime_against_women_type'] = df['crime_against_women_type'].str.replace(' ', '', regex=False)
df['crime_against_women_type'].unique()

array(['8,10', 'NotApplicable', '10', '9', '4,7', '4', '7', '1,10', '8',
       '3', '7,10', '2,3,6', '6', '1,4,10', '2', '5,6', '5', '11', '2,3',
       '7,9', '3,7,10', '2,6', '1', '4,8', '3,7', '3,8', '7,8', '1,4',
       '6,8', '4,7,10', '8,9'], dtype=object)

In [11]:
df[df['crime_against_women_type'] == '11'][['city', 'title', 'text']]

,city,title,text
155,Ghaziabad,"Ghaziabad: ‘Auto gang’ robs woman of cash, mobile",GHAZIABAD: A 40-year-old woman was allegedly r...
233,Kanpur,"Woman killed for honour in UP, body recovered ...",KANPUR: In the rising spate of honour killings...
234,Kanpur,Woman thrashed on suspicion of child-lifting i...,KANPUR: A mentally unstable elderly woman was ...

In [12]:
df['crime_against_women_type'] = df['crime_against_women_type'].replace('11', 'Other/Undocumented')
df['crime_against_women_type'].unique()

array(['8,10', 'NotApplicable', '10', '9', '4,7', '4', '7', '1,10', '8',
       '3', '7,10', '2,3,6', '6', '1,4,10', '2', '5,6', '5',
       'Other/Undocumented', '2,3', '7,9', '3,7,10', '2,6', '1', '4,8',
       '3,7', '3,8', '7,8', '1,4', '6,8', '4,7,10', '8,9'], dtype=object)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['calculated_adult_total'] = df['murder_male_adult_victims'] + df['murder_female_adult_victims'] + df['kidnap_male_adult_victims'] + df['kidnap_female_adult_victims']

mismatch_adult = df[df['total_adult_victims'] != df['calculated_adult_total']]
mismatch_adult[['title', 'total_adult_victims', 'calculated_adult_total']]

,title,total_adult_victims,calculated_adult_total
7,Stalker threatens B.Tech student over wedding ...,1,0
11,"Woman found dead in room, live-in partner missing",0,1
13,‘Friendship’ on Facebook ends in blackmail plo...,1,0
20,"Body found in drain, cops suspect murder",0,1
29,"Ghaziabad: Girl resists molestation, kin attacked",1,0
...,...,...,...
460,"Rae Bareli woman alleges rape, seeks CM Yogi A...",1,0
461,"Top cop stirs row, says girl filed case after ...",1,0
462,Unnao girl passes away after 40-hour battle fo...,1,0
464,Uttar Pradesh: Woman accuses boss of harassment,1,0
465,Buyer knifes fish vendor to death over Rs 10 i...,0,1

In [15]:
mismatch_adult['has_caw_code']= mismatch_adult.index.map(lambda i: df.loc[i, 'crime_against_women_type'] != 'Not Applicable')
mismatch_adult['has_caw_code'].value_counts()

C:\Users\HONOR\AppData\Local\Temp\ipykernel_20776\1060517022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mismatch_adult['has_caw_code']= mismatch_adult.index.map(lambda i: df.loc[i, 'crime_against_women_type'] != 'Not Applicable')

has_caw_code
True    252
Name: count, dtype: int64

In [16]:
df = df.drop(columns=['calculated_adult_total'])

# Sanity check: no negative values anywhere in numeric columns
numeric_cols = ['murder_child_victims', 'murder_male_adult_victims', 'murder_female_adult_victims',
                 'kidnap_child_victims', 'kidnap_male_adult_victims', 'kidnap_female_adult_victims',
                 'total_adult_victims', 'total_child_victims']

(df[numeric_cols] < 0).sum()

murder_child_victims           0
murder_male_adult_victims      0
murder_female_adult_victims    0
kidnap_child_victims           0
kidnap_male_adult_victims      0
kidnap_female_adult_victims    0
total_adult_victims            0
total_child_victims            0
dtype: int64

In [17]:
df['total_victims'] = df['murder_child_victims'] + df['murder_male_adult_victims'] + df['murder_female_adult_victims'] + df['kidnap_child_victims'] + df['kidnap_male_adult_victims'] + df['kidnap_female_adult_victims'] + df['total_adult_victims'] + df['total_child_victims']

df['crime_category'] = np.select(
    [
        df['murder_reason'] != 'Not Applicable',
        df['crime_against_women_type'] != 'Not Applicable',
        (df['kidnap_child_victims'] + df['kidnap_male_adult_victims'] + df['kidnap_female_adult_victims']) > 0
    ],
    ['Murder', 'Crime Against Women', 'Kidnapping'],
    default='Unclassified'
)

df['crime_category'].value_counts()

crime_category
Crime Against Women    319
Murder                 147
Name: count, dtype: int64

In [18]:
df = df[['city', 'title', 'text', 'crime_category', 'total_victims',
         'murder_reason', 'murder_child_victims', 'murder_male_adult_victims', 'murder_female_adult_victims',
         'kidnap_child_victims', 'kidnap_male_adult_victims', 'kidnap_female_adult_victims',
         'crime_against_women_type', 'total_adult_victims', 'total_child_victims']]

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466 entries, 0 to 465
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   city                         466 non-null    object
 1   title                        466 non-null    object
 2   text                         466 non-null    object
 3   crime_category               466 non-null    object
 4   total_victims                466 non-null    int64
 5   murder_reason                466 non-null    object
 6   murder_child_victims         466 non-null    int64
 7   murder_male_adult_victims    466 non-null    int64
 8   murder_female_adult_victims  466 non-null    int64
 9   kidnap_child_victims         466 non-null    int64
 10  kidnap_male_adult_victims    466 non-null    int64
 11  kidnap_female_adult_victims  466 non-null    int64
 12  crime_against_women_type     466 non-null    object
 13  total_adult_victims          466 non-null    int64
 14  total_child_victims          466 non-null    int64
dtypes: int64(9), object(6)
memory usage: 54.7+ KB

,city,title,text,crime_category,total_victims,murder_reason,murder_child_victims,murder_male_adult_victims,murder_female_adult_victims,kidnap_child_victims,kidnap_male_adult_victims,kidnap_female_adult_victims,crime_against_women_type,total_adult_victims,total_child_victims
0,Ghaziabad,"Minor molests mute girl, sent to observation home",GHAZIABAD: A 12-year-old boy was sent to an ob...,Crime Against Women,3,Not Applicable,0,0,0,0,0,0,"8,10",0,3
1,Ghaziabad,Family out to buy car robbed of Rs 1 lakh by b...,GHAZIABAD: A family that had visited an automo...,Crime Against Women,0,Not Applicable,0,0,0,0,0,0,NotApplicable,0,0
2,Ghaziabad,"This gang posed as cops to extort youths, couples",GHAZIABAD: Five persons were arrested on Monda...,Crime Against Women,0,Not Applicable,0,0,0,0,0,0,NotApplicable,0,0
3,Ghaziabad,"Residents object to loud music, thrashed in Gh...","Ghaziabad: Four tenants, including two soldier...",Crime Against Women,0,Not Applicable,0,0,0,0,0,0,NotApplicable,0,0
4,Ghaziabad,Man kills self after being refused money for d...,GHAZIABAD: A 25-year-old allegedly committed s...,Crime Against Women,0,Not Applicable,0,0,0,0,0,0,NotApplicable,0,0

In [19]:
df['crime_against_women_type'] = df['crime_against_women_type'].replace('NotApplicable', 'Not Applicable')

df['crime_category'] = np.select(
    [
        df['murder_reason'] != 'Not Applicable',
        df['crime_against_women_type'] != 'Not Applicable',
        (df['kidnap_child_victims'] + df['kidnap_male_adult_victims'] + df['kidnap_female_adult_victims']) > 0
    ],
    ['Murder', 'Crime Against Women', 'Kidnapping'],
    default='Unclassified'
)

df['crime_category'].value_counts()

crime_category
Crime Against Women    195
Murder                 147
Unclassified           106
Kidnapping              18
Name: count, dtype: int64

In [21]:
df.to_csv('crime_data_clean.csv', index=False)
print("Saved:",df.shape)

Saved: (466, 15)

In [22]:
df['city'].value_counts()

city
Lucknow      202
Ghaziabad    167
Kanpur        97
Name: count, dtype: int64